### ISSUE TITLE
Code Execution

### ISSUE THREAD

**Issue by Phaite** [gaozhanheng/Vertebra-Body-Segmentation#1]
Hi,
The repo doesn't contain the DICOM files referred to in the code. Can you please upload the files?

**Comment by Phaite** [comment]
I get this error when i run it on a DICOM file i downloaded from a spine ct repo. Can you help?
```
C:\Users\NC\Downloads\Compressed\Vertebra-Body-Segmentation-master\Vertebra-Body-Segmentation-master\icp\transformations.py:1899: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
Total time running 'loadMesh': 0.159999847412 seconds
Traceback (most recent call last):
  File "VBSegmentation.py", line 120, in <module>
    main()
  File "VBSegmentation.py", line 32, in main
    dicomImage = loadDICOM(dicominfo)
  File "C:\Users\NC\Downloads\Compressed\Vertebra-Body-Segmentation-master\Vertebra-Body-Segmentation-master\utilities\utilities.py", line 130, in function_timer
    result = function(*args, **kwargs)
  File "C:\Users\NC\Downloads\Compressed\Vertebra-Body-Segmentation-master\Vertebra-Body-Segmentation-master\utilities\utilities.py", line 457, in loadDICOM
    allDicoms = [int(os.path.splitext(file)[0]) for file in allfiles if os.path.splitext(file)[1].lower() == '.dcm']
ValueError: invalid literal for int() with base 10: 'I00001'
```
